### ISSUE TITLE
Plot does not update continuously

### ISSUE THREAD

**Issue by gintriago12** [jacobmontiel/skmultiflow-demo#1]
Dear Jacob,

When I run a demo for scikit-learn, I dont get the plot to update continuously. See the figure below. Please, your help.
<img width="641" alt="1" src="https://user-images.githubusercontent.com/17325256/78089161-6459cd80-737b-11ea-96f5-a7699709a14f.png">

**Comment by gintriago12** [comment]
Btw, I am using spyder.

**Comment by jacobmontiel** [comment]
Hi @gintriago12 

Spyder uses an `iPython` console, so you need to use a `matplotlib` backend that works with `iPython`.

I did an experiment and it works with [`GTK3`](https://www.gtk.org/), you need to run the following at the beginning of your script:

```python
%matplotlib gtk3
```

It might work with other backend but haven't tried.

**Comment by gintriago12** [comment]
Hi Jacob, I tried to install gtk3 but I found it very hard. Also, I tried your code in jupyter notebook but had the same issue as I showed to you in my first message.

**Comment by gintriago12** [comment]
<img width="785" alt="imagen" src="https://user-images.githubusercontent.com/17325256/78200383-5b343380-7443-11ea-90b5-58287b64a3b7.png">

**Comment by jacobmontiel** [comment]
To show dynamic plots within a Jupyter notebook you need to run in the first cell:

```
​%​matplotlib notebook
```
